#Save as dnsmasq-project.conf; substitute actual values
port=53
listen-address=127.0.0.1,10.7.17.71
bind-interfaces
no-hosts
no-resolv
local=/divyansh.test/
host-record=app.divyansh.test,10.7.17.165,60
host-record=api.divyansh.test,10.7.17.165,60
log-queries
log-facility=-

