events {
    worker_connections 256;
}

http {
    # Error log
    error_log /Users/vanshjain/Desktop/CN-project-phase-1/04_evidence/Mac2/logs/error.log warn;

    upstream team_backends {
        server 10.7.5.3:3001 max_fails=1 fail_timeout=5s;
        server 10.7.11.219:3002 max_fails=1 fail_timeout=5s;
    }

    server {
        listen 443 ssl;
        server_name app.divyansh.test api.divyansh.test;

        # Access log
        access_log /Users/vanshjain/Desktop/CN-project-phase-1/04_evidence/Mac2/logs/access.log;

        ssl_certificate /Users/vanshjain/Desktop/CN-project-phase-1/02_config/team-cert.pem;
        ssl_certificate_key /Users/vanshjain/Desktop/CN-project-phase-1/02_config/team-key.pem;

        ssl_protocols TLSv1.2 TLSv1.3;

        location / {
            proxy_pass http://team_backends;

            proxy_set_header Host $host;

            proxy_connect_timeout 2s;
            proxy_read_timeout 5s;

            proxy_next_upstream error timeout http_502 http_503 http_504;
            proxy_next_upstream_tries 2;
        }
    }
}